# Generated by Django 2.2.11 on 2020-04-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nozolanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='provider',
            table='"nozolan_provider"',
        ),
    ]
