const DefaultProvider = {
  name: '',
  description: '',
  address: '',
  city: '',
  state: '',
  zip: '',
  phone: '',
  email: '',
  contact: '',
  website: '',
  facebook: '',
  instagram: '',
  twitter: '',
  logo: '',
  vertical: 'bottom',
  horizontal: 'center',
  open: false,
  nameError: false,
  cityError: false,
  stateError: false,
  logoError: false,
};

export default DefaultProvider;
