# Generated by Django 2.0.6 on 2019-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=8000)),
                ('logo', models.ImageField(default='no-img.jpg', upload_to='providers')),
                ('date_created', models.DateField(max_length=8, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
