# Generated by Django 2.0.6 on 2019-08-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='provider',
            table='provider',
        ),
    ]
