# Generated by Django 2.0.6 on 2019-08-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190819_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=8000)),
                ('image', models.ImageField(default='no-img.jpg', upload_to='providers')),
                ('date_created', models.DateField(max_length=8, null=True)),
                ('active', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='home.Provider')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
