# Generated by Django 2.0.6 on 2019-08-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='no-img.jpg', upload_to='offers'),
        ),
    ]
