# Generated by Django 2.0.6 on 2019-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190823_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(default='', max_length=8000),
            preserve_default=False,
        ),
    ]
